version: '3.8'

# For YP-ers we can make it easer by setting SIAB_USE_PPK=true and all PASSWORD_ACCESS=false
# the default public private keys will then be used


services:
  shellinabox:
    image: ivonet/shellinabox:latest
    environment:
      - USER_NAME=ivonet
      - PASSWORD=secret
      - SUDO_ACCESS=true
    hostname: steppingstone
    ports:
      - 8080:4200
    networks:
      - frontend
      - backend

  host1:
    image: ivonet/openssh:latest
    build: .
    environment:
      - PUID=1000
      - PGID=1000
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true # if set to false the default keys will be used
      - USER_NAME=ivonet #optional
      - USER_PASSWORD=secret #optional
    hostname: host1
    networks:
      - backend
    restart: unless-stopped




networks:
  frontend:
  backend:

