version: '3.8'

# For YP-ers we can make it easer by setting SIAB_USE_PPK=true and all PASSWORD_ACCESS=false
# the default public private keys will then be used


services:
  shellinabox:
    image: ivonet/shellinabox:latest
    environment:
      - SIAB_ADDUSER=true
      - SIAB_USER=ivonet
      - SIAB_GROUP=ivonet
      - SIAB_PASSWORD=secret
      - SIAB_SUDO=false # Enable sudo for the steppingstone?
      - SIAB_USE_PPK=false #Use Pre-generated Public Private keys?
      - SIAB_SSL=false
    ports:
      - 8080:4200
    networks:
      - frontend
      - backend

  host1:
    image: ivonet/openssh:latest
    build: .
    environment:
      - PUID=1000
      - PGID=1000
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true # if set to false the default keys will be used
      - USER_NAME=ivonet #optional
      - USER_PASSWORD=secret #optional
    networks:
      - backend
    restart: unless-stopped

#  host2:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host4:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host5:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped

#  host6:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host7:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host8:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host9:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host10:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host11:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host12:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host13:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host14:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped
#
#  host15:
#    image: ivonet/openssh:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=true
#      - USER_NAME=ivonet #optional
#      - USER_PASSWORD=secret #optional
#    networks:
#      - backend
#    restart: unless-stopped


networks:
  frontend:
  backend:

