version: '3.8'

services:
  shellinabox:
    image: ivonet/shellinabox:latest
    environment:
      - SIAB_SUDO=true
      - SIAB_ADDUSER=true
      - SIAB_USER=ivonet
      - SIAB_USERID=1000
      - SIAB_GROUP=ivonet
      - SIAB_GROUPID=1000
      - SIAB_PASSWORD=secret
      - SIAB_SHELL=/bin/bash
      - SIAB_HOME=/home/ivonet
      - SIAB_SUDO=false
    #  - SIAB_PORT=4200
    #  - SIAB_SERVICE=/:LOGIN
    #  - SIAB_PKGS=none
    #  - SIAB_SCRIPT=none
    ports:
      - 8080:4200
    networks:
      - frontend
      - backend

  terminal1:
    image: ivonet/terminal:latest
    build: .
    environment:
      - PUID=1000
      - PGID=1000
      - PUBLIC_KEY_FILE=/opt/ssh/id_rsa.pub #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=false #optional
      - USER_NAME=ivonet #optional
      - USER_PASSWORD=secret #optional
    networks:
      - backend
    restart: unless-stopped

#  terminal2:
#    image: ivonet/terminal:latest
#    build: .
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - PUBLIC_KEY_FILE=/opt/ssh/id_rsa.pub #optional
#      - SUDO_ACCESS=true #optional
#      - PASSWORD_ACCESS=false #optional
#      - USER_PASSWORD=secret #optional
##      - USER_PASSWORD_FILE=/path/to/file #optional
#      - USER_NAME=guest #optional
#    networks:
#      - backend
#    restart: unless-stopped

networks:
  frontend:
  backend:

