#!/command/with-contenv bash

USER_NAME=${USER_NAME:-ivonet.nl}

PUID=${PUID:-911}
PGID=${PGID:-911}

[[ "$USER_NAME" != "abc" ]] && \
    usermod -l "$USER_NAME" abc && \
    groupmod -n "$USER_NAME" abc

groupmod -o -g "$PGID" "$USER_NAME"
usermod -o -u "$PUID" -m -d "/home/$USER_NAME" "$USER_NAME"

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u "$USER_NAME")
User gid:    $(id -g "$USER_NAME")
-------------------------------------
"
chown -R "$USER_NAME":"$USER_NAME" /app
chown -R "$USER_NAME":"$USER_NAME" /config
chown -R "$USER_NAME":"$USER_NAME" /defaults
